import React, { useState } from 'react';
import { 
  X, 
  Printer, 
  Copy, 
  Check, 
  TrendingUp, 
  ShieldCheck, 
  Dumbbell, 
  Briefcase, 
  CheckCircle2, 
  FileText,
  Calendar,
  Sparkles
} from 'lucide-react';
import { EvolveState } from '../types';
import { calculateFinancialMetrics } from '../services/smartEngine';
import { getTbilisiTodayDate, getDaysDifference } from '../utils/date';

interface ExecutiveReportModalProps {
  state: EvolveState;
  onClose: () => void;
  onOpenLiveVoice?: () => void;
}

export function ExecutiveReportModal({
  state,
  onClose,
  onOpenLiveVoice,
}: ExecutiveReportModalProps) {
  const [copied, setCopied] = useState(false);
  const today = getTbilisiTodayDate();
  const metrics = calculateFinancialMetrics(state);

  const mainProject = state.projects.find(p => p.isWeeklyMainProject);
  const completedTasks = state.tasks.filter(t => t.status === 'Done');
  const pendingTasks = state.tasks.filter(t => t.status !== 'Done');
  const activeClients = state.clients.filter(c => c.stage === 'Active' || c.stage === 'Negotiating');
  const totalWorkouts = state.workoutSessions.length;
  
  // Deliverables progress
  const deliverables = mainProject?.deliverables || [];
  const completedDeliverables = deliverables.filter(d => d.completed);

  // Generate clean Markdown text
  const generateMarkdown = () => {
    return `# EVOLVE OS — EXECUTIVE SUMMARY REPORT
**Date:** ${today} | **Timezone:** Asia/Tbilisi | **Target:** ₾6,000 / month recurring

---

## 1. FINANCIAL PERFORMANCE & CASH PIPELINE
- **Cash Received This Cycle:** ₾${metrics.receivedIncome.toLocaleString()}
- **Expected Cash (Active Follow-ups):** ₾${metrics.expectedIncome.toLocaleString()}
- **Pipeline Potential:** ₾${metrics.pipelineTotal.toLocaleString()}
- **Monthly Recurring Target Progress:** ${Math.round((metrics.receivedIncome / 6000) * 100)}% of ₾6,000/mo

## 2. WEEKLY MAIN PROJECT
- **Project:** ${mainProject ? mainProject.name : 'None designated'}
- **Deliverables Completed:** ${completedDeliverables.length} / ${deliverables.length} (${deliverables.length > 0 ? Math.round((completedDeliverables.length / deliverables.length) * 100) : 0}%)
- **Immediate Next Action:** ${mainProject?.nextAction || 'None'}

## 3. CLIENT CRM & ACCOUNTS
${activeClients.map(c => `- **${c.name}** (${c.stage}): Expected ₾${c.expectedRevenue}, Next Action: "${c.nextAction || 'None'}" [Due: ${c.nextActionDate || 'N/A'}]`).join('\n')}

## 4. EXECUTION THROUGHPUT
- **Completed Tasks:** ${completedTasks.length}
- **Active Pending Tasks:** ${pendingTasks.length}
- **Critical / High Priority Remaining:** ${pendingTasks.filter(t => t.priority === 'Critical' || t.priority === 'High').length}

## 5. PHYSICAL VITALITY & TRAINING
- **Completed Workout Sessions:** ${totalWorkouts} sessions logged
- **Weekly Target:** 5 sessions (Upper / Lower / Recovery / Calisthenics)

---
*Generated by EVOLVE OS Decision Engine*
`;
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(generateMarkdown());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/85 backdrop-blur-md animate-in fade-in duration-200">
      <div className="bg-neutral-900 border border-neutral-800 w-full max-w-3xl rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[92vh]">
        
        {/* Header */}
        <div className="p-5 border-b border-neutral-800 flex items-center justify-between bg-neutral-950/60 print:hidden">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-cyan-500/10 border border-cyan-500/20 text-cyan-400 flex items-center justify-center">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-base font-semibold text-white tracking-tight">Weekly Executive Report</h3>
              <p className="text-xs text-neutral-400">
                Printable dossier and Markdown export of operational, financial, and physical metrics
              </p>
            </div>
          </div>
          
          <div className="flex items-center gap-2">
            {onOpenLiveVoice && (
              <button
                onClick={() => {
                  onClose();
                  onOpenLiveVoice();
                }}
                className="hidden sm:flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30 hover:bg-emerald-500/30 transition"
              >
                <Sparkles className="w-3.5 h-3.5" />
                Spar with Chief of Staff
              </button>
            )}

            <button
              onClick={handleCopy}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-medium bg-neutral-800 hover:bg-neutral-700 text-neutral-200 border border-neutral-700 transition"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied' : 'Copy Markdown'}</span>
            </button>

            <button
              onClick={handlePrint}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold bg-neutral-100 hover:bg-white text-black transition shadow"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print / PDF</span>
            </button>

            <button
              onClick={onClose}
              className="text-neutral-400 hover:text-white p-2 rounded-lg hover:bg-neutral-800 transition ml-2"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Printable Report Canvas */}
        <div id="printable-executive-report" className="flex-1 overflow-y-auto p-6 sm:p-8 space-y-6 text-neutral-200 print:text-black print:bg-white print:p-0">
          
          {/* Report Title & Metadata */}
          <div className="border-b border-neutral-800 pb-5">
            <div className="flex items-center justify-between">
              <span className="text-[11px] font-mono tracking-widest text-emerald-400 uppercase font-semibold">
                EVOLVE OS // EXECUTIVE DOSSIER
              </span>
              <span className="text-xs font-mono text-neutral-400">
                DATE: {today} (Tbilisi)
              </span>
            </div>
            <h1 className="text-2xl font-bold text-white tracking-tight mt-1">
              Cycle Operations & Performance Summary
            </h1>
            <p className="text-xs text-neutral-400 mt-1">
              Target: ₾6,000/mo recurring retainer cash flow • Weekly Main Project execution • Health consistency
            </p>
          </div>

          {/* Section 1: Financial Performance */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 text-xs font-mono font-semibold uppercase text-neutral-400 tracking-wider">
              <TrendingUp className="w-4 h-4 text-emerald-400" />
              <span>1. Cash & Revenue Performance</span>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-4 gap-3 font-mono">
              <div className="p-3.5 rounded-xl bg-neutral-950 border border-neutral-800">
                <div className="text-[10px] text-emerald-400 uppercase">Received Cash</div>
                <div className="text-xl font-bold text-emerald-400 mt-1">₾{metrics.receivedIncome.toLocaleString()}</div>
                <div className="text-[10px] text-neutral-500 mt-0.5">Direct cash in bank</div>
              </div>

              <div className="p-3.5 rounded-xl bg-neutral-950 border border-neutral-800">
                <div className="text-[10px] text-amber-400 uppercase">Expected Milestone</div>
                <div className="text-xl font-bold text-amber-400 mt-1">₾{metrics.expectedIncome.toLocaleString()}</div>
                <div className="text-[10px] text-neutral-500 mt-0.5">Immediate follow-up pipeline</div>
              </div>

              <div className="p-3.5 rounded-xl bg-neutral-950 border border-neutral-800">
                <div className="text-[10px] text-blue-400 uppercase">Pipeline Potential</div>
                <div className="text-xl font-bold text-blue-400 mt-1">₾{metrics.pipelineTotal.toLocaleString()}</div>
                <div className="text-[10px] text-neutral-500 mt-0.5">Active leads & proposals</div>
              </div>

              <div className="p-3.5 rounded-xl bg-neutral-950 border border-neutral-800">
                <div className="text-[10px] text-cyan-400 uppercase">Monthly Goal (₾6k)</div>
                <div className="text-xl font-bold text-cyan-400 mt-1">
                  {Math.round((metrics.receivedIncome / 6000) * 100)}%
                </div>
                <div className="text-[10px] text-neutral-500 mt-0.5">Recurring target pace</div>
              </div>
            </div>
          </div>

          {/* Section 2: Weekly Main Project */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 text-xs font-mono font-semibold uppercase text-neutral-400 tracking-wider">
              <Briefcase className="w-4 h-4 text-cyan-400" />
              <span>2. Weekly Main Project Status</span>
            </div>

            {mainProject ? (
              <div className="p-4 rounded-xl bg-neutral-950 border border-neutral-800 space-y-3">
                <div className="flex items-start justify-between">
                  <div>
                    <h3 className="text-sm font-semibold text-neutral-100">{mainProject.name}</h3>
                    <p className="text-xs text-neutral-400 mt-0.5">{mainProject.description}</p>
                  </div>
                  <span className="text-xs font-mono px-2.5 py-1 rounded bg-cyan-950 text-cyan-300 border border-cyan-800">
                    {deliverables.length > 0 ? Math.round((completedDeliverables.length / deliverables.length) * 100) : 0}% Done
                  </span>
                </div>

                <div className="text-xs text-neutral-300">
                  <div className="text-[10px] font-mono uppercase text-neutral-500 mb-1">Deliverables Breakdown</div>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                    {deliverables.map(d => (
                      <div key={d.id} className="flex items-center gap-2 p-2 rounded-lg bg-neutral-900 border border-neutral-800/80">
                        {d.completed ? (
                          <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
                        ) : (
                          <div className="w-4 h-4 rounded border border-neutral-600 shrink-0" />
                        )}
                        <span className={`text-xs ${d.completed ? 'line-through text-neutral-500' : 'text-neutral-200'}`}>
                          {d.title}
                        </span>
                      </div>
                    ))}
                  </div>
                </div>

                {mainProject.nextAction && (
                  <div className="pt-2 border-t border-neutral-850 flex items-center justify-between text-xs">
                    <span className="text-neutral-400">Next critical action:</span>
                    <span className="font-semibold text-emerald-400 font-mono">{mainProject.nextAction}</span>
                  </div>
                )}
              </div>
            ) : (
              <div className="p-4 rounded-xl bg-neutral-950 border border-neutral-800 text-xs text-neutral-500 italic">
                No Weekly Main Project currently designated.
              </div>
            )}
          </div>

          {/* Section 3: CRM Accounts & Follow-ups */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 text-xs font-mono font-semibold uppercase text-neutral-400 tracking-wider">
              <ShieldCheck className="w-4 h-4 text-purple-400" />
              <span>3. CRM & Client Follow-up Health</span>
            </div>

            <div className="space-y-2">
              {activeClients.map(c => (
                <div key={c.id} className="p-3.5 rounded-xl bg-neutral-950 border border-neutral-800 flex flex-col sm:flex-row sm:items-center justify-between gap-2 text-xs">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="font-semibold text-neutral-100">{c.name}</span>
                      <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-neutral-800 text-neutral-300">
                        {c.stage}
                      </span>
                      {c.company && <span className="text-neutral-500 text-[11px]">• {c.company}</span>}
                    </div>
                    {c.nextAction && (
                      <div className="text-neutral-400 mt-1">
                        Next: <span className="text-neutral-200 font-medium">{c.nextAction}</span>
                      </div>
                    )}
                  </div>
                  <div className="flex sm:flex-col items-end gap-1 font-mono text-[11px]">
                    <span className="text-amber-400 font-semibold">Expected: ₾{c.expectedRevenue.toLocaleString()}</span>
                    {c.nextActionDate && (
                      <span className={`text-[10px] ${c.nextActionDate <= today ? 'text-rose-400 font-semibold' : 'text-neutral-500'}`}>
                        Due: {c.nextActionDate}
                      </span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Section 4: Physical Consistency */}
          <div className="space-y-3">
            <div className="flex items-center gap-2 text-xs font-mono font-semibold uppercase text-neutral-400 tracking-wider">
              <Dumbbell className="w-4 h-4 text-orange-400" />
              <span>4. Physical Training & Health Discipline</span>
            </div>

            <div className="p-4 rounded-xl bg-neutral-950 border border-neutral-800 flex items-center justify-between text-xs">
              <div>
                <div className="font-semibold text-neutral-200">
                  {totalWorkouts} Workout Sessions Completed
                </div>
                <p className="text-neutral-400 mt-0.5">
                  Calisthenics, core stability, and athletic mobility blocks maintained.
                </p>
              </div>
              <span className="font-mono text-xs px-3 py-1.5 rounded-lg bg-orange-500/10 text-orange-400 border border-orange-500/20">
                Consistency: {Math.min(100, Math.round((totalWorkouts / 5) * 100))}%
              </span>
            </div>
          </div>

          {/* Footer note */}
          <div className="pt-4 border-t border-neutral-800 text-center text-[10px] font-mono text-neutral-500">
            EVOLVE OS // BUILT FOR HIGH-LEVERAGE DECISION MAKING AND UNCOMPROMISING EXECUTION
          </div>

        </div>

      </div>
    </div>
  );
}
